#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# Always run from the repo root (its instructions and .env path assume it).
cd "$(dirname "$0")/.."

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

LIVE_SIGNING_KEY_FILE="${LIVE_SIGNING_KEY_FILE:-$HOME/moat-signing-key-DO-NOT-COMMIT/live-signing-private-key.pem}"
RELEASE_TAG="v0.11.90"

banner "Moat: launch setup"

# ── Stage 1: Chrome Web Store developer account ───────────────────────────
stage "Chrome Web Store: developer account"
say "One-time signup + a \$5 registration fee Google charges once, ever."
open_url "https://chrome.google.com/webstore/devconsole/register"
step "Sign in with the Google account you want to publish Moat under."
step "Pay the one-time \$5 registration fee when prompted."
step "When asked to declare Trader / Non-trader status, select Non-trader --"
step "a private individual, no registered business, no monetization today."
note "You can switch to Trader later, any time, if you ever monetize -- this isn't permanent."
confirm "Account created and the \$5 fee paid?" || warn "come back to this stage before continuing"

# ── Stage 2: create the CWS item, get Publisher ID + Extension ID ─────────
stage "Chrome Web Store: create the item"
say "This gets you the two IDs (publisher, extension) the publish workflow needs."
say "Grab chrome.zip from the draft GitHub Release first, if you haven't already:"
open_url "https://github.com/Samuelabhinav37/moat/releases/tag/${RELEASE_TAG}"
step "Download chrome.zip from that release page."
open_url "https://chrome.google.com/webstore/devconsole"
step "Click 'New Item', upload chrome.zip. Leave it as a draft -- do NOT submit"
step "for review yet, we're only creating the listing to get its ID."
step "Once created, look at the dashboard URL or the item's own page:"
note "  the Item ID is the long id in the URL, e.g. .../detail/abcdefghijklmnop"
step "Fill in whatever store-listing fields it insists on to save the draft"
step "(docs/store-listing.md in the repo has ready-to-paste copy for these)."
step "The Publisher ID is shown under Account → Developer Public Profile,"
step "or in Account settings."
ask CWS_PUBLISHER_ID "Paste the Publisher ID:"
ask CWS_EXTENSION_ID "Paste the Extension/Item ID:"

# ── Stage 3: Google Cloud OAuth credentials for the CWS API ───────────────
stage "Chrome Web Store: API credentials"
say "This is the fiddly one -- Google has no single button for it. Following"
say "the exact steps from fregante/chrome-webstore-upload-keys (the standard"
say "community tool for this), verified against its current README."
open_url "https://console.developers.google.com/apis/credentials"
step "Create a new project (any name, e.g. 'chrome-webstore-upload')."
open_url "https://console.cloud.google.com/auth/overview"
step "Click 'Get started'. Enter an app name + your email."
step "When asked for the audience: select Internal if it's offered."
note "  A personal (non-Workspace) Gmail account often only offers 'External'"
note "  instead -- if so, pick External, then add yourself as a test user"
note "  when it asks. Either way, fill in required fields until Create works."
step "Click 'Create OAuth client' → type 'Desktop app' → name it anything →"
step "Create. Save the Client ID shown."
step "Open that same client's details (Info button) and save the Client Secret."
open_url "https://console.cloud.google.com/apis/library/chromewebstore.googleapis.com"
step "Click 'Enable' on the Chrome Web Store API page."
say ""
say "Now run this in a NEW terminal (needs Node.js -- it opens a browser and"
say "a local server to finish the OAuth handshake; don't close it early):"
note "  npx chrome-webstore-upload-keys"
step "Paste your Client ID and Client Secret when it asks, approve the consent"
step "screen in the browser tab it opens, then copy the refreshToken it prints."
pause "Run that now in another terminal, then come back here."
ask CWS_CLIENT_ID "Paste CLIENT_ID:"
ask_secret CWS_CLIENT_SECRET "Paste CLIENT_SECRET:"
ask_secret CWS_REFRESH_TOKEN "Paste the refreshToken:"
set_secret CWS_CLIENT_ID "$CWS_CLIENT_ID"
set_secret CWS_CLIENT_SECRET "$CWS_CLIENT_SECRET"
set_secret CWS_REFRESH_TOKEN "$CWS_REFRESH_TOKEN"
set_secret CWS_PUBLISHER_ID "$CWS_PUBLISHER_ID"
set_secret CWS_EXTENSION_ID "$CWS_EXTENSION_ID"

# ── Stage 4: Firefox AMO account + API keys ───────────────────────────────
stage "Firefox Add-ons (AMO): account + API keys"
open_url "https://addons.mozilla.org/developers/"
step "Sign up / sign in as a Firefox extension developer. No fee for AMO."
open_url "https://addons.mozilla.org/developers/addon/api/key/"
step "Click 'Generate new credentials' under Manage API Keys."
step "Copy the JWT issuer and JWT secret it shows you (shown once)."
ask AMO_JWT_ISSUER "Paste the JWT issuer:"
ask_secret AMO_JWT_SECRET "Paste the JWT secret:"
set_secret AMO_JWT_ISSUER "$AMO_JWT_ISSUER"
set_secret AMO_JWT_SECRET "$AMO_JWT_SECRET"

# ── Stage 5: live-update manifest signing ─────────────────────────────────
stage "Live-update channel: turn on signing"
say "The signing keypair is already generated. The public half is already"
say "committed. Only the private half, sitting on this machine, is left."
if [[ -f "$LIVE_SIGNING_KEY_FILE" ]]; then
  step "Found the private key at: $LIVE_SIGNING_KEY_FILE"
  if confirm "Set it as the LIVE_SIGNING_PRIVATE_KEY GitHub secret now?"; then
    if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
      gh secret set LIVE_SIGNING_PRIVATE_KEY < "$LIVE_SIGNING_KEY_FILE" \
        && printf '  %s✓ set%s GitHub secret LIVE_SIGNING_PRIVATE_KEY\n' "$GREEN" "$RESET" \
        || warn "gh secret set failed -- set it by hand (see below)"
    else
      SKIPPED+=("GitHub secret LIVE_SIGNING_PRIVATE_KEY (gh not ready)")
      warn "gh not ready -- set it by hand: gh secret set LIVE_SIGNING_PRIVATE_KEY < \"$LIVE_SIGNING_KEY_FILE\""
    fi
  fi
else
  warn "Key file not found at $LIVE_SIGNING_KEY_FILE -- generate one with:"
  note "  node scripts/gen-live-signing-key.mjs"
fi
say ""
say "Now, in your OWN terminal (not through Claude -- this touches the raw"
say "private key, which is exactly the kind of thing it shouldn't handle),"
say "run this once to actually sign the live manifest:"
note "  LIVE_SIGNING_PRIVATE_KEY=\"\$(cat $LIVE_SIGNING_KEY_FILE)\" npm run filters:update"
note "  git add live/manifest.json.sig && git commit -m \"Sign the live-update manifest\" && git push"
pause "Run those two lines now, then come back."
if confirm "Delete the local plaintext private-key file now that it's in GitHub + used?"; then
  rm -f "$LIVE_SIGNING_KEY_FILE" && say "  deleted." || warn "couldn't delete it -- remove it by hand later"
else
  note "Left in place. It's outside the repo already, but keep it somewhere you control -- never commit it."
fi

# ── Stage 6: smoke-test, then a beta dry run ───────────────────────────────
stage "Smoke-test, then a beta dry run"
step "Reload the unpacked extension (chrome://extensions → reload icon on Moat),"
step "or unzip and load dist/chrome fresh. Click through Settings once:"
note "  Protection tab full-width until you click a row, Filter Lists shows"
note "  the renamed lists, Pick an element actually starts the picker."
confirm "Smoke-tested and it looks right?" || warn "fix that before publishing anything for real"
say ""
say "With all 7 secrets set, trigger a BETA dry run (CWS trusted testers +"
say "AMO unlisted) before going stable -- this is what the channel input is for."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if confirm "Run: gh workflow run publish.yml -f ref=${RELEASE_TAG} -f targets=both -f channel=beta ?"; then
    gh workflow run publish.yml -f ref="${RELEASE_TAG}" -f targets=both -f channel=beta \
      && say "  triggered. Watch it: gh run watch" \
      || warn "trigger failed -- run it from the repo's Actions tab instead"
  fi
else
  note "gh not ready -- trigger it from the Actions tab on GitHub instead:"
  note "  Actions → Publish to stores → Run workflow → ref=${RELEASE_TAG}, channel=beta"
fi

# ── Stage 7: publish the draft GitHub release ─────────────────────────────
stage "Publish the draft release"
open_url "https://github.com/Samuelabhinav37/moat/releases/tag/${RELEASE_TAG}"
step "Review the draft release notes and attached zips/checksums."
step "Once you're happy (and the beta dry run above looked right), click"
step "'Edit', then 'Publish release'."
note ""
note "One thing NOT covered here because it's a decision, not a task:"
note "Ghostery TrackerDB (used for the 'By company' feature) is licensed"
note "non-commercial-only. If you ever monetize Moat, get an actual"
note "attorney's read on that before you do -- see NOTICE.md."
confirm "Published?" && say "  Live." || note "No rush -- come back to this whenever."
# ──────────────────────────────────────────────────────────────────────────

finish
