#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Run from the repository root, wherever the script is started from.
cd "$(dirname "$0")/.."
REPO="Samuelabhinav37/moat-reports"
WRANGLER="npx -y wrangler@4"
CONFIG="report-worker/wrangler.toml"

banner "Moat report service setup"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "GitHub: private reports repository"
say "Problem reports are filed as issues in a private repository that only you can read."
if gh repo view "$REPO" >/dev/null 2>&1; then
  say "$REPO already exists. Nothing to do here."
else
  say "This creates $REPO as a PRIVATE repository on your account."
  if confirm "Create $REPO now?"; then
    gh repo create "$REPO" --private --description "Problem reports sent from the Moat extension" >/dev/null
    printf '  %s✓ created%s %s\n' "$GREEN" "$RESET" "$REPO"
  else
    SKIPPED+=("create the private repo $REPO")
  fi
fi
pause

# ── 2 ────────────────────────────────────────────────────────────────────
stage "GitHub: a token that can only file issues there"
say "The report service needs a token that can open issues in $REPO and nothing else."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: moat-reports worker. Pick an expiration (a year is fine; you'll re-run this to renew)."
step "Resource owner: your account (Samuelabhinav37)."
step "Repository access: 'Only select repositories', then choose moat-reports."
step "Permissions, Repository permissions: set 'Issues' to 'Read and write'. Leave everything else as is."
step "Generate the token and copy it (it starts with github_pat_)."
ask_secret REPORTS_GITHUB_TOKEN "Paste the token:"
code=$(curl -s -o /dev/null -w '%{http_code}' -H "Authorization: Bearer $REPORTS_GITHUB_TOKEN" "https://api.github.com/repos/$REPO/issues?per_page=1")
if [[ "$code" == "200" ]]; then
  printf '  %s✓ token can read %s issues%s\n' "$GREEN" "$REPO" "$RESET"
else
  warn "GitHub answered $code for that token. Check it has Issues access to $REPO, then re-run."
  exit 1
fi
write_env REPORTS_GITHUB_TOKEN "$REPORTS_GITHUB_TOKEN"
pause

# ── 3 ────────────────────────────────────────────────────────────────────
stage "Cloudflare: log in"
say "The report service runs as a free Cloudflare Worker. Wrangler (Cloudflare's CLI) needs to log in once."
if $WRANGLER whoami 2>/dev/null | grep -qi "associated with the email"; then
  say "Wrangler is already logged in."
else
  step "A browser window opens. Sign in to Cloudflare (or create a free account) and click Allow."
  $WRANGLER login
fi
pause

# ── 4 ────────────────────────────────────────────────────────────────────
stage "Cloudflare: deploy the report service"
say "This deploys report-worker/ as 'moat-reports' on your workers.dev address,"
say "then stores the token as the Worker's GITHUB_TOKEN secret."
note "If your account has no workers.dev subdomain yet, Wrangler asks you to pick one."
if confirm "Deploy now?"; then
  out=$($WRANGLER deploy --config "$CONFIG" 2>&1 | tee /dev/stderr)
  REPORT_ENDPOINT=$(printf '%s' "$out" | grep -oE 'https://[a-z0-9.-]+\.workers\.dev' | head -n1)
  if [[ -z "$REPORT_ENDPOINT" ]]; then
    ask REPORT_ENDPOINT "Couldn't spot the URL above. Paste the https://...workers.dev address:"
  fi
  printf '%s' "$REPORTS_GITHUB_TOKEN" | $WRANGLER secret put GITHUB_TOKEN --config "$CONFIG"
  write_env REPORT_ENDPOINT "$REPORT_ENDPOINT"
else
  ask REPORT_ENDPOINT "Already deployed? Paste its https://...workers.dev address:"
  write_env REPORT_ENDPOINT "$REPORT_ENDPOINT"
fi
pause

# ── 5 ────────────────────────────────────────────────────────────────────
stage "Test: send one report"
say "This sends one test report, the way the extension does. It becomes an issue in $REPO"
say "titled 'Problem on wizard-test.example' that you can close afterwards."
if confirm "Send the test report?"; then
  body='{"v":1,"category":"other","hostname":"wizard-test.example","note":"Setup test from scripts/report-setup-wizard.sh. Safe to close.","moatVersion":"0.0.0","browser":"Other","level":"standard","lists":[],"pausingFixes":"untried"}'
  reply=$(curl -s -X POST "$REPORT_ENDPOINT" \
    -H "origin: chrome-extension://moatsetupwizardtest" -H "x-moat-report: 1" -H "content-type: application/json" \
    --data "$body")
  if printf '%s' "$reply" | grep -q '"id":"R-'; then
    printf '  %s✓ report service answered%s %s\n' "$GREEN" "$RESET" "$reply"
    open_url "https://github.com/$REPO/issues"
  else
    warn "Unexpected answer: $reply"
    warn "Check the token (stage 2) and the secret (stage 4), then re-run."
    exit 1
  fi
else
  SKIPPED+=("send a test report to $REPORT_ENDPOINT")
fi
pause

# ── 6 ────────────────────────────────────────────────────────────────────
stage "Moat: point the report page at the service"
say "Writes the address into src/shared/reportEndpoint.ts, so the report page sends"
say "straight to it (and Settings > About lists problem reports as a data flow)."
sed -i.bak -E "s#^export const REPORT_ENDPOINT = \".*\";#export const REPORT_ENDPOINT = \"$REPORT_ENDPOINT\";#" src/shared/reportEndpoint.ts
rm -f src/shared/reportEndpoint.ts.bak
grep -n "REPORT_ENDPOINT =" src/shared/reportEndpoint.ts | sed 's/^/  /'
say "Next: tell Claude it's done. It builds, checks and commits this with the privacy"
say "policy update as the next version."
pause "Press Enter to finish."

finish
